language: php
dist: trusty
php:
    - "7.4"
    - "master"
    - "nightly"
matrix:
    fast_finish: true
    allow_failures:
        - php: "master"
        - php: "nightly"
install:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml
    - ./vendor/bin/psalm
after_success:
    - bash <(curl -s https://codecov.io/bash)
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
